server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://192.168.50.190:3406/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.0.148:3406/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ahogek
    password: 123456
  redis:
#    host: 192.168.50.190 # Redis服务器地址
    host: 192.168.0.148
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
    key:
      prefix:
        authCode: "portal:authCode:"
      expire:
        authCode: 120 # 验证码超期时间

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.cml

logging:
  level:
    com.example.learnmalldemo.mbg.mapper: debug