server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.50.26:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.50.26 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
    key:
      prefix:
        authCode: 'portal:authCode:'
      expire:
        authCode: 120 # 验证码超期时间
  security:
    filter:
      order: 10
  data:
    mongodb:
      database: mall-port
      uri: mongodb://root:123456@192.168.50.26:27017
  rabbitmq:
    host: 192.168.50.26
    port: 5672
    username: mall
    password: mall
    virtual-host: /mall
  elasticsearch:
    rest:
      uris: http://192.168.50.26:9200
      password: 123456
      username: elastic

logging:
  level:
    com.example.learnmalldemo.mapper: debug
    org.springframework.security: warn
    org.springframework.data.convert.CustomConversions: error
  pattern:
    console: '[%d{dd/MM/yy hh:mm:ss:sss z}] %t %5p %c{2}: %m%n'

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: AhogeK7577259 #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头