server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.50.190:3406/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.0.105:3406/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ahogek
    password: 123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.cml

logging:
  level:
    com.example.learnmalldemo.mbg.mapper: debug